Feature/ldap password
neo4j/helm-charts pull request #162
Opened 2023-04-05 15:53 UTC by harshitsinghvi22

2023-04-05 16:06 UTC, ojhughes requested changes

2023-04-05 16:06 UTC, ojhughes commented on neo4j/templates/_ldap.tpl
> +                {{ fail (printf "Secret %s configured in 'neo4j.ldapPasswordFromSecret' not found" .Values.ldapPasswordFromSecret) }}
`neo4j.ldapPasswordFromSecret` is inconsistent with the values.yaml.

2023-04-05 16:06 UTC, ojhughes commented on neo4j/templates/neo4j-config.yaml
> +  dbms.security.ldap.authorization.system_password: "{{ $ldapPassword }}"
I don't think we should do this... We are forced to lookup the secret which can break things for user.

I think it would be better to use expanded config to read the secret from a file eg ` dbms.security.ldap.authorization.system_password: $(cat /secret/myldappassword.txt)`

2023-04-05 16:10 UTC, ojhughes commented on neo4j/templates/neo4j-config.yaml
> +  dbms.security.ldap.authorization.system_password: "{{ $ldapPassword }}"
It also means we end up keeping the secret in plain text in the config map

2023-04-05 16:24 UTC, harshitsinghvi22 commented on neo4j/templates/_ldap.tpl
> +                {{ fail (printf "Secret %s configured in 'neo4j.ldapPasswordFromSecret' not found" .Values.ldapPasswordFromSecret) }}
Good catch..will fix it

2023-04-06 11:43 UTC, harshitsinghvi22 commented on neo4j/templates/neo4j-config.yaml
> +  dbms.security.ldap.authorization.system_password: "{{ $ldapPassword }}"
implemented the suggestion

2023-04-06 12:41 UTC, ojhughes approved these changes, later dismissed

2023-04-11 07:55 UTC, merged